//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenericServiceClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericRepoOfCategoryfQKzcaVM", Namespace="http://schemas.datacontract.org/2004/07/GenericServiceLib")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GenericServiceClient.ServiceReference1.CategoryRepo))]
    public partial class GenericRepoOfCategoryfQKzcaVM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryRepo", Namespace="http://schemas.datacontract.org/2004/07/GenericServiceLib.Repos")]
    [System.SerializableAttribute()]
    public partial class CategoryRepo : GenericServiceClient.ServiceReference1.GenericRepoOfCategoryfQKzcaVM {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericRepoOfManufacturerfQKzcaVM", Namespace="http://schemas.datacontract.org/2004/07/GenericServiceLib")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GenericServiceClient.ServiceReference1.ManufacturerRepo))]
    public partial class GenericRepoOfManufacturerfQKzcaVM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManufacturerRepo", Namespace="http://schemas.datacontract.org/2004/07/GenericServiceLib.Repos")]
    [System.SerializableAttribute()]
    public partial class ManufacturerRepo : GenericServiceClient.ServiceReference1.GenericRepoOfManufacturerfQKzcaVM {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IContract")]
    public interface IContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContract/GetCategories", ReplyAction="http://tempuri.org/IContract/GetCategoriesResponse")]
        GenericServiceClient.ServiceReference1.CategoryRepo GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContract/GetCategories", ReplyAction="http://tempuri.org/IContract/GetCategoriesResponse")]
        System.Threading.Tasks.Task<GenericServiceClient.ServiceReference1.CategoryRepo> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContract/GetManufacturers", ReplyAction="http://tempuri.org/IContract/GetManufacturersResponse")]
        GenericServiceClient.ServiceReference1.ManufacturerRepo GetManufacturers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContract/GetManufacturers", ReplyAction="http://tempuri.org/IContract/GetManufacturersResponse")]
        System.Threading.Tasks.Task<GenericServiceClient.ServiceReference1.ManufacturerRepo> GetManufacturersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContractChannel : GenericServiceClient.ServiceReference1.IContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContractClient : System.ServiceModel.ClientBase<GenericServiceClient.ServiceReference1.IContract>, GenericServiceClient.ServiceReference1.IContract {
        
        public ContractClient() {
        }
        
        public ContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GenericServiceClient.ServiceReference1.CategoryRepo GetCategories() {
            return base.Channel.GetCategories();
        }
        
        public System.Threading.Tasks.Task<GenericServiceClient.ServiceReference1.CategoryRepo> GetCategoriesAsync() {
            return base.Channel.GetCategoriesAsync();
        }
        
        public GenericServiceClient.ServiceReference1.ManufacturerRepo GetManufacturers() {
            return base.Channel.GetManufacturers();
        }
        
        public System.Threading.Tasks.Task<GenericServiceClient.ServiceReference1.ManufacturerRepo> GetManufacturersAsync() {
            return base.Channel.GetManufacturersAsync();
        }
    }
}
